# exposes port 80 of the application to localhost:80 inside app services
version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    image: backend:1.0

  frontend:
    container_name: frontend
    image: frontend:1.0
    build:
      context: ./web
      dockerfile: prod.Dockerfile

  ml:
    container_name: ml
    image: ml:1.0
    build: "./ml"

  proxy:
    container_name: proxy
    build: ./proxy
    image: proxy:1.0
