# exposes port 8080 of the application to localhost:80 inside app services
version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    ports:
      - '27017:27017'