# exposes port 80 of the application to localhost:80 inside app services
version: "3"
services:
  app:
    container_name: insaaf
    build: "./backend"
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - DATABASE=mongodb://mongo/insaaf
      - DATABASE_TEST=mongodb://mongo/insaaf-test
      - DATABASE_DEVELOPMENT=mongodb://mongo/insaaf-dev
      - PORT=8080
      - PORT_DEVELOPMENT=8080
      - PORT_TEST=8080
      - NODE_ENV=PRODUCTION
  web:
    container_name: web
    build: "./web"
    ports:
      - "8081:3000"
    links:
      - app
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
