# exposes port 80 of the application to localhost:80 inside app services
version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    image: containerService/backend:1.0

  frontend:
    container_name: frontend
    image: containerService/frontend:1.0
    build:
      context: ./web
      dockerfile: prod.Dockerfile

  ml:
    container_name: ml
    image: containerService/ml:1.0
    build: "./ml"
