# exposes port 80 of the application to localhost:80 inside app services
version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    image: ${CONTAINER_REGISTRY}/insaaf_backend:${version}

  frontend:
    container_name: frontend
    image: ${CONTAINER_REGISTRY}/insaaf_frontend:${version}
    build:
      context: ./web
      dockerfile: prod.Dockerfile

  ml:
    container_name: ml
    image: ${CONTAINER_REGISTRY}/insaaf_ml:${version}
    build: "./ml"

  proxy:
    container_name: proxy
    build: ./proxy
    image: ${CONTAINER_REGISTRY}/insaaf_proxy:${version}
