# exposes port 80 of the application to localhost:80 inside app services
version: "3"
services:
  backend:
    container_name: backend
    image: backend:1.0
    # image: insaaf.azurecr.io/insaaf_backend:latest
    ports:
      - "8080:8080"
    links:
      - ml
    environment:
      - DATABASE=mongodb+srv://azure:ffuMTF4QcdTOrsUF@digitalipcv1-5ahez.mongodb.net/insaaf?retryWrites=true&w=majority
      - PORT=8080
      - NODE_ENV=PRODUCTION
      - ML_URL=http://ml:5000

  frontend:
    container_name: frontend
    image: frontend:1.0
    # image: insaaf.azurecr.io/insaaf_frontend:latest
    ports:
      - "8081:3000"
    links:
      - backend
      - ml

  proxy:
    container_name: proxy
    image: proxy:1.0
    # image: insaaf.azurecr.io/insaaf_proxy:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - frontend

  ml:
    container_name: ml
    image: ml:1.0
    # image: insaaf.azurecr.io/insaaf_ml:latest
    ports:
      - "5000:5000"
