# on: [push]
# name: BuildImages

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     # checkout the repo
#     - name: 'Checkout GitHub Action'
#       uses: actions/checkout@master
    
#     - uses: azure/docker-login@v1
#       with:
#         login-server: insaaf.azurecr.io
#         username: ${{ secrets.REGISTRY_USERNAME }}
#         password: ${{ secrets.REGISTRY_PASSWORD }}
#     - run: |
#         docker build ${{github.workspace}}/backend/ --file backend/prod.Dockerfile -t insaaf.azurecr.io/insaaf_backend:${{ github.sha }}
#         docker push insaaf.azurecr.io/insaaf_backend:${{ github.sha }}
#         docker build ${{github.workspace}}/web/ -f web/prod.Dockerfile -t insaaf.azurecr.io/insaaf_frontend:${{ github.sha }}
#         docker push insaaf.azurecr.io/insaaf_frontend:${{ github.sha }}
#         docker build ${{github.workspace}}/proxy/ --file proxy/Dockerfile -t insaaf.azurecr.io/insaaf_proxy:${{ github.sha }}
#         docker push insaaf.azurecr.io/insaaf_proxy:${{ github.sha }}
#         docker build ${{github.workspace}}/ml/ --file ml/Dockerfile -t insaaf.azurecr.io/insaaf_ml:${{ github.sha }}
#         docker push insaaf.azurecr.io/insaaf_ml:${{ github.sha }} 